#!/usr/bin/expect -f
set inf [lindex $argv 0];
set outf [lindex $argv 1];
spawn xmlsec1 --sign --output $outf --privkey-pem privateKey.pem,publicCert.pem $inf
expect {
-re ".*sword.*" {
exp_send "lubba10580\r"
exp_continue
}
}
