# encoding: utf-8
Account.find_or_create_by(codigo: "1010101", nombre: "CAJA CONSEJO GENERAL")
Account.find_or_create_by(codigo: "1010102", nombre: "CAJA CONSEJO REGIONAL IQUIQUE")
Account.find_or_create_by(codigo: "1010103", nombre: "CAJA CONSEJO REGIONAL ANTOFAGASTA")
Account.find_or_create_by(codigo: "1010104", nombre: "CAJA CONSEJO REGIONAL LA SERENA")
Account.find_or_create_by(codigo: "1010105", nombre: "CAJA CONSEJO REGIONAL VALPARAISO")
Account.find_or_create_by(codigo: "1010106", nombre: "CAJA CONSEJO REGIONAL SANTIAGO")
Account.find_or_create_by(codigo: "1010107", nombre: "CAJA CONSEJO REGIONAL RANCAGUA")
Account.find_or_create_by(codigo: "1010108", nombre: "CAJA CONSEJO REGIONAL TALCA")
Account.find_or_create_by(codigo: "1010109", nombre: "CAJA CONSEJO REGIONAL CONCEPCION")
Account.find_or_create_by(codigo: "1010110", nombre: "CAJA CONSEJO REGIONAL TEMUCO")
Account.find_or_create_by(codigo: "1010111", nombre: "CAJA CONSEJO REGIONAL VALDIVIA")
Account.find_or_create_by(codigo: "1010112", nombre: "CAJA CONSEJO REGIONAL PUERTO MONTT")
Account.find_or_create_by(codigo: "1010113", nombre: "CAJA CONSEJO REGIONAL PUNTA ARENAS")
Account.find_or_create_by(codigo: "1010114", nombre: "CAJA SUBSEDE COPIAPO")
Account.find_or_create_by(codigo: "1010115", nombre: "CAJA SUBSEDE OSORNO")
Account.find_or_create_by(codigo: "1010116", nombre: "CAJA SUBSEDE ARICA")
Account.find_or_create_by(codigo: "1010117", nombre: "CAJA REGIONAL AYSEN ")
Account.find_or_create_by(codigo: "1010118", nombre: "CAJA REGIONAL CHILOE")
Account.find_or_create_by(codigo: "1010119", nombre: "SUB SEDE CHILLAN ÑUBLE")
Account.find_or_create_by(codigo: "1010120", nombre: "CAJA FENECH")
Account.find_or_create_by(codigo: "1010121", nombre: "CAJA SUB SEDE LINARES")
Account.find_or_create_by(codigo: "1010122", nombre: "CAJA SUB SEDE  BIO BIO ")
Account.find_or_create_by(codigo: "1010201", nombre: "FONDO FIJO SECRETARIA")
Account.find_or_create_by(codigo: "1010202", nombre: "FONDO FIJO CENTRO DOCUMENTACION")
Account.find_or_create_by(codigo: "1010301", nombre: "BANCO DE CHILE CONSEJO GENERAL")
Account.find_or_create_by(codigo: "1010302", nombre: "BANCO DEL ESTADO CONSEJO GENERAL")
Account.find_or_create_by(codigo: "1020101", nombre: "DEPOSITOS EN PESOS")
Account.find_or_create_by(codigo: "1020102", nombre: "DEPOSITOS A PLAZO EN U.F.")
Account.find_or_create_by(codigo: "1020103", nombre: "DEPOSITOS A PLAZO EN US$")
Account.find_or_create_by(codigo: "1020104", nombre: "DEPOSITOS Y AHORROS REGIONALES")
Account.find_or_create_by(codigo: "1020201", nombre: "AHORROS EN PESOS")
Account.find_or_create_by(codigo: "1020202", nombre: "AHORROS EN U.F.")
Account.find_or_create_by(codigo: "1020203", nombre: "AHORROS EN US$")
Account.find_or_create_by(codigo: "1030101", nombre: "ACCIONES")
Account.find_or_create_by(codigo: "1030102", nombre: "MAYOR Y MENOR VALOR VALORES NEGOCIABLES")
Account.find_or_create_by(codigo: "1040101", nombre: "CUOTAS SOCIALES POR COBRAR")
Account.find_or_create_by(codigo: "1040201", nombre: "PRESTAMOS OTORGADOS POR COBRAR")
Account.find_or_create_by(codigo: "1040301", nombre: "PRESTAMO CONSEJO REGIONAL VALPARAISO")
Account.find_or_create_by(codigo: "1040302", nombre: "PRESTAMO CONSEJO REGIONAL SANTIAGO")
Account.find_or_create_by(codigo: "1040303", nombre: "PRESTAMO CONSEJO REGIONAL VALDIVIA")
Account.find_or_create_by(codigo: "1040304", nombre: "PRESTAMO CONSEJO REGIONAL TEMUCO")
Account.find_or_create_by(codigo: "1040305", nombre: "PRESTAMO CONSEJO REGIONAL PUNTA ARENAS ")
Account.find_or_create_by(codigo: "1040306", nombre: "PRESTAMO CONSEJO REGIONAL CONCEPCION")
Account.find_or_create_by(codigo: "1050101", nombre: "LETRAS POR COBRAR")
Account.find_or_create_by(codigo: "1050102", nombre: "CHEQUES POR COBRAR")
Account.find_or_create_by(codigo: "1050103", nombre: "OTROS DOCUMENTOS POR COBRAR")
Account.find_or_create_by(codigo: "1060101", nombre: "DONACIONES POR RECIBIR")
Account.find_or_create_by(codigo: "1070101", nombre: "ANTICIPO DE SUELDOS")
Account.find_or_create_by(codigo: "1070102", nombre: "PRESTAMOS AL PERSONAL")
Account.find_or_create_by(codigo: "1070103", nombre: "FONDOS A RENDIR")
Account.find_or_create_by(codigo: "1080101", nombre: "ARTICULOS DE ESCRITORIO")
Account.find_or_create_by(codigo: "1080102", nombre: "ARTICULOS DE ASEO")
Account.find_or_create_by(codigo: "1080201", nombre: "INSIGNIAS DE ORO")
Account.find_or_create_by(codigo: "1080202", nombre: "ARTICULOS VARIOS")
Account.find_or_create_by(codigo: "1090101", nombre: "SEGUROS")
Account.find_or_create_by(codigo: "1110101", nombre: "ACTIVOS CON RESTRICCIONES")
Account.find_or_create_by(codigo: "1210101", nombre: "TERRENOS")
Account.find_or_create_by(codigo: "1220101", nombre: "BIEN RAIZ MIRAFLORES 563")
Account.find_or_create_by(codigo: "1220102", nombre: "BIEN RAIZ VALPARAISO")
Account.find_or_create_by(codigo: "1220103", nombre: "BIEN RAIZ TALCA")
Account.find_or_create_by(codigo: "1220104", nombre: "BIEN RAIZ CONCEPCION")
Account.find_or_create_by(codigo: "1220105", nombre: "BIEN RAIZ TEMUCO")
Account.find_or_create_by(codigo: "1220106", nombre: "BIEN RAIZ VALDIVIA")
Account.find_or_create_by(codigo: "1230101", nombre: "ACTIVOS EN LEASING")
Account.find_or_create_by(codigo: "1240101", nombre: "COMPUTADORES")
Account.find_or_create_by(codigo: "1240102", nombre: "FOTOCOPIADORAS")
Account.find_or_create_by(codigo: "1240103", nombre: "OTROS EQUIPOS")
Account.find_or_create_by(codigo: "1250101", nombre: "MUEBLES")
Account.find_or_create_by(codigo: "1260101", nombre: "OTROS ACTIVOS FIJOS")
Account.find_or_create_by(codigo: "1270101", nombre: "DEPRECIACION ACUMULADA ACTIVOS EN LEASING")
Account.find_or_create_by(codigo: "1270102", nombre: "DEPRECIACION ACUMULADA EQUIPOS")
Account.find_or_create_by(codigo: "1270103", nombre: "DEPRECIACION ACUMULADA MUEBLES")
Account.find_or_create_by(codigo: "1270104", nombre: "DEPRECIACION ACUMULADA OTROS ACTIVOS FIJOS")
Account.find_or_create_by(codigo: "1280101", nombre: "ACTIVOS FIJOS RESTRINGIDOS PARA INVERTIR")
Account.find_or_create_by(codigo: "1310101", nombre: "INVERSIONES A LARGO PLAZO")
Account.find_or_create_by(codigo: "1320101", nombre: "DONACIONES POR RECIBIR")
Account.find_or_create_by(codigo: "1330101", nombre: "ACTIVOS CON RESTRICCIONES")
Account.find_or_create_by(codigo: "2010101", nombre: "OBLIGACIONES CON BANCOS C/P")
Account.find_or_create_by(codigo: "2020101", nombre: "OBLIGACIONES CON BANCOS PORCION LARGO PLAZO")
Account.find_or_create_by(codigo: "2030101", nombre: "CHILECTRA")
Account.find_or_create_by(codigo: "2030102", nombre: "COMPAÑÍA DE TELEFONOS")
Account.find_or_create_by(codigo: "2030103", nombre: "CORREOS DE CHILE")
Account.find_or_create_by(codigo: "2030104", nombre: "GASCO")
Account.find_or_create_by(codigo: "2030105", nombre: "EMOS")
Account.find_or_create_by(codigo: "2030201", nombre: "CUENTAS VARIAS")
Account.find_or_create_by(codigo: "2030202", nombre: "SUELDOS POR PAGAR")
Account.find_or_create_by(codigo: "2030203", nombre: "HONORARIOS POR PAGAR")
Account.find_or_create_by(codigo: "2040101", nombre: "ACREEDORES VARIOS")
Account.find_or_create_by(codigo: "2040102", nombre: "CONTROL CUOTAS ORDINARIAS")
Account.find_or_create_by(codigo: "2040103", nombre: "REINTEGROS POR REALIZAR")
Account.find_or_create_by(codigo: "2040104", nombre: "ENFERMERA AYUDA A ENFERMERA (TERREMOTO 2010)")
Account.find_or_create_by(codigo: "2050101", nombre: "SOCIEDAD DE PEDIATRIA")
Account.find_or_create_by(codigo: "2050102", nombre: "SOCIEDAD DE SALUD MENTAL")
Account.find_or_create_by(codigo: "2050103", nombre: "SOCIEDAD DE CARDIOLOGIA")
Account.find_or_create_by(codigo: "2050104", nombre: "SOCIEDAD DE PAB.QUIRURGICOS")
Account.find_or_create_by(codigo: "2050105", nombre: "SOCIEDAD DE EDUCACION")
Account.find_or_create_by(codigo: "2050106", nombre: "SOCIEDAD DE NEUROCIRUGIA")
Account.find_or_create_by(codigo: "2050107", nombre: "SOCIEDAD DE HEMODIALISIS")
Account.find_or_create_by(codigo: "2050201", nombre: "AFP")
Account.find_or_create_by(codigo: "2050202", nombre: "ISAPRES")
Account.find_or_create_by(codigo: "2050203", nombre: "FONASA")
Account.find_or_create_by(codigo: "2050204", nombre: "CAJA DE COMPENSACION")
Account.find_or_create_by(codigo: "2050301", nombre: "IMPUESTO SEGUNDA CATEGORIA")
Account.find_or_create_by(codigo: "2050302", nombre: "IMPUESTO UNICO")
Account.find_or_create_by(codigo: "2050401", nombre: "OTRAS RETENCIONES")
Account.find_or_create_by(codigo: "2060101", nombre: "PROVISIONES")
Account.find_or_create_by(codigo: "2110101", nombre: "OBLIGACIONES CON BANCOS")
Account.find_or_create_by(codigo: "2120101", nombre: "OBLIGACIONES CON LEASING")
Account.find_or_create_by(codigo: "2210101", nombre: "PATRIMONIO SIN RESTRICCIONES")
Account.find_or_create_by(codigo: "2210102", nombre: "REVALORIZACION PATRIMONIO SIN RESTRICCIONES")
Account.find_or_create_by(codigo: "2220101", nombre: "PATRIMONIO CON RESTRICCIONES TEMPORALES")
Account.find_or_create_by(codigo: "2220102", nombre: "REVALORIZACION PATRIMONIO CON RESTR. TEMPORALES")
Account.find_or_create_by(codigo: "2230101", nombre: "PATRIMONIO CON RESTRICCIONES PERMANENTES")
Account.find_or_create_by(codigo: "2230102", nombre: "REVALORIZACION PATRIMONIO CON RESTR. PERMANENTES")
Account.find_or_create_by(codigo: "2240101", nombre: "EXEDENTE DEL EJERCICIO")
Account.find_or_create_by(codigo: "3110101", nombre: "INGRESOS POR DONACIONES Y APORTES NACIONALES")
Account.find_or_create_by(codigo: "3110201", nombre: "INGRESOS POR DONACIONES Y APORTES EXTRANJEROS")
Account.find_or_create_by(codigo: "3110301", nombre: "OTROS APORTES")
Account.find_or_create_by(codigo: "3210101", nombre: "CUOTAS SOCIALES")
Account.find_or_create_by(codigo: "3210201", nombre: "INSCRIPCIONES")
Account.find_or_create_by(codigo: "3210202", nombre: "REINSCRIPCIONES")
Account.find_or_create_by(codigo: "3210203", nombre: "CERTIFICADOS DE EXTRANJERIA")
Account.find_or_create_by(codigo: "3210301", nombre: "INSCRPCIONES CONGRESO")
Account.find_or_create_by(codigo: "3310101", nombre: "CARNET PROFESIONAL")
Account.find_or_create_by(codigo: "3310102", nombre: "INSIGNIAS CORRIENTES")
Account.find_or_create_by(codigo: "3310103", nombre: "PLACAS PARA AUTOMOVILES")
Account.find_or_create_by(codigo: "3310104", nombre: "CODIGOS DE ETICA")
Account.find_or_create_by(codigo: "3310105", nombre: "ARTICULOS VARIOS")
Account.find_or_create_by(codigo: "3310201", nombre: "VENTA ARTICULOS CONGRESO")
Account.find_or_create_by(codigo: "3310301", nombre: "OTROS INGRESOS POR VENTAS")
Account.find_or_create_by(codigo: "3410101", nombre: "INTERESES EN DEPOSITOS A PLAZO")
Account.find_or_create_by(codigo: "3410102", nombre: "MAYOR VALOR INVERSIONES VALORES NEGOCIABLES")
Account.find_or_create_by(codigo: "3410103", nombre: "DIVIDENDOS DE ACCIONES")
Account.find_or_create_by(codigo: "3410201", nombre: "INTERESES PRESTAMOS OTORGADOS")
Account.find_or_create_by(codigo: "3510101", nombre: "OTROS INGRESOS")
Account.find_or_create_by(codigo: "3510102", nombre: "INGRESOS POR ARRIENDOS")
Account.find_or_create_by(codigo: "3510103", nombre: "INGRESOS POR RECUPERACION DE GASTOS")
Account.find_or_create_by(codigo: "3510104", nombre: "RECUPERACION GASTOS REVISTA")
Account.find_or_create_by(codigo: "3610101", nombre: "CORRECCION MONETARIA")
Account.find_or_create_by(codigo: "4010101", nombre: "COSTO ARTICULOS COLEGIADOS")
Account.find_or_create_by(codigo: "4110101", nombre: "SUELDOS")
Account.find_or_create_by(codigo: "4110102", nombre: "HORAS EXTRAORDINARIAS")
Account.find_or_create_by(codigo: "4110103", nombre: "ASIGNACION  MOVILIZACION Y COLACION")
Account.find_or_create_by(codigo: "4110104", nombre: "AGUINALDOS Y BONOS")
Account.find_or_create_by(codigo: "4110105", nombre: "FINIQUITOS")
Account.find_or_create_by(codigo: "4110106", nombre: "LEY ACCIDENTES DEL TRABAJO")
Account.find_or_create_by(codigo: "4110201", nombre: "HONORARIOS POR ASESORIAS PERMANENTES")
Account.find_or_create_by(codigo: "4110202", nombre: "HONORARIOS ESPORADICOS")
Account.find_or_create_by(codigo: "4110203", nombre: "HONORARIOS POR PROYECTOS")
Account.find_or_create_by(codigo: "4210101", nombre: "LUZ")
Account.find_or_create_by(codigo: "4210102", nombre: "AGUA")
Account.find_or_create_by(codigo: "4210103", nombre: "TELEFONO")
Account.find_or_create_by(codigo: "4210104", nombre: "GAS")
Account.find_or_create_by(codigo: "4210105", nombre: "FRANQUEO")
Account.find_or_create_by(codigo: "4210201", nombre: "ARTICULOS DE OFICINA")
Account.find_or_create_by(codigo: "4210202", nombre: "ARTICULOS DE ASEO")
Account.find_or_create_by(codigo: "4210203", nombre: "INTERNET")
Account.find_or_create_by(codigo: "4220101", nombre: "SUSCRIPCIONES")
Account.find_or_create_by(codigo: "4220201", nombre: "SERVICIOS FONASA")
Account.find_or_create_by(codigo: "4220301", nombre: "MANTENCION COMPUTADORES")
Account.find_or_create_by(codigo: "4220302", nombre: "MANTENCION FOTOCOPIADORAS")
Account.find_or_create_by(codigo: "4220303", nombre: "MANTENCION EQUIPOS VARIOS")
Account.find_or_create_by(codigo: "4220401", nombre: "MANTENCION EDIFICIO MIRAFLORES")
Account.find_or_create_by(codigo: "4220402", nombre: "MANTENCION SEDES")
Account.find_or_create_by(codigo: "4220501", nombre: "FOTOCOPIAS")
Account.find_or_create_by(codigo: "4220601", nombre: "IMPUESTOS Y OTROS")
Account.find_or_create_by(codigo: "4220701", nombre: "SEGUROS")
Account.find_or_create_by(codigo: "4220801", nombre: "ARRIENDOS")
Account.find_or_create_by(codigo: "4220901", nombre: "OTROS GASTOS")
Account.find_or_create_by(codigo: "4230101", nombre: "GASTOS ADMINISTRATIVOS")
Account.find_or_create_by(codigo: "4240101", nombre: "CAPACITACION PERSONAL")
Account.find_or_create_by(codigo: "4240102", nombre: "CAPACITACION COLEGIADOS")
Account.find_or_create_by(codigo: "4250101", nombre: "VIATICOS")
Account.find_or_create_by(codigo: "4250102", nombre: "PASAJES Y MOVILIZACION")
Account.find_or_create_by(codigo: "4250103", nombre: "RELACIONES PUBLICAS")
Account.find_or_create_by(codigo: "4250104", nombre: "HOTELES Y ALOJAMIENTOS")
Account.find_or_create_by(codigo: "4250105", nombre: "ALIMENTACION")
Account.find_or_create_by(codigo: "4250106", nombre: "PRESENTES RECORDATORIOS")
Account.find_or_create_by(codigo: "4250107", nombre: "SERVICIOS DE ONCES")
Account.find_or_create_by(codigo: "4250108", nombre: "APORTES VARIOS")
Account.find_or_create_by(codigo: "4250109", nombre: "GASTOS VARIOS POR ACCION GREMIAL")
Account.find_or_create_by(codigo: "4250110", nombre: "PASAJES AEREOS - TERRESTRES")
Account.find_or_create_by(codigo: "4250111", nombre: "PASAJE VIAJE CONSEJERAS NACIONAL ")
Account.find_or_create_by(codigo: "4250112", nombre: "E- LEARNING")
Account.find_or_create_by(codigo: "4250115", nombre: "PAGOS POR INTERNATIONAL COUNCIL OF NURSES   CIE. ")
Account.find_or_create_by(codigo: "4250201", nombre: "REVISTA ENFERMERAS")
Account.find_or_create_by(codigo: "4250202", nombre: "PUBLICACIONES VARIAS")
Account.find_or_create_by(codigo: "4250203", nombre: "IMPRESOS")
Account.find_or_create_by(codigo: "4250301", nombre: "HONORARIOS ACCION GREMIAL")
Account.find_or_create_by(codigo: "4260101", nombre: "CASTIGO CUOTAS SOCIALES")
Account.find_or_create_by(codigo: "4260201", nombre: "CASTIGO PRESTAMOS OTORGADOS")
Account.find_or_create_by(codigo: "4310101", nombre: "DEPRECIACION  DEL EJERCICIO")
Account.find_or_create_by(codigo: "4410101", nombre: "GASTOS FINANCIEROS")
Account.find_or_create_by(codigo: "4510101", nombre: "CORRECCION MONETARIA")
